const MAJOR_VERSION_NUMBER = 1;
const MINOR_VERSION_NUMBER = 0;
export const VERSION_NUMBER = `${MAJOR_VERSION_NUMBER}.${MINOR_VERSION_NUMBER}.${
  import.meta.env.VITE_BUILD_NUMBER || 0
}.${import.meta.env.VITE_REVISION_NUMBER || 0}`;
